language: Python
Python:
  - 3.8

jobs:
  inlude:
    - stage: Flask-API
      services:
        - docker
      before_script: pip install docker-compose
      script:
        - docker-compose up --build

    - stage: Test-Script
      services:
        - docker
      script:
        - docker run jnewton1452/test-script
