language: Python
Python:
  - 3.8

stage:
  - Flask-API
  - Test-Script

jobs:
  inlude:
    - stage: Flask-API
      services:
        - docker
      before_script: pip install docker-compose pyyaml
      name: API
      script:
        - docker-compose up --build -d
        - python3 ./Test-Script/Test.py
