language: Python
Python:
  - 3.8

stage:
  - Flask-API
  - Test-Script

jobs:
  inlude:
    - stage: Flask-API
      services:
        - docker
      before_script: pip install docker-compose
      name: API
      script:
        - docker-compose up --build
      
      name: Test-Script
      script:
        - docker run --net=host jnewton1452/test-script


      
