language: Python
Python:
  - 3.8

stage:
  - Flask-API
  - docker-compose push

jobs:
  inlude:
    - stage: Flask-API
      services:
        - docker
      before_script:
        - pip install docker-compose pyyaml colorama
        - pip install "requests[security]"
        - chmod +x ./Test-Script/test.yaml
      name: API
      script:
        - docker-compose up --build -d
        - python3 ./Test-Script/Test.py
        - docker-compose down
    - stage: docker-compose
      services:
        - docker
      before_script:
        - pip install docker-compose
      script:
        - bash ./Docker-Bash-Script
