language: Python
Python:
  - 3.8

stage:
  - Flask-API
  - Test-Script

jobs:
  inlude:
    - stage: Flask-API
      services:
        - docker
      before_script:
        - pip install docker-compose pyyaml colorama
        - sudo python3 -m pip install "requests[security]"
        - chmod +x ./Test-Script/test.yaml
      name: API
      script:
        - docker-compose up --build -d
        - python3 ./Test-Script/Test.py
