language: Python
Python:
  - 3.8

jobs:
  inlude:
    - stage: "Flask-API"
      services:
        - docker
      before_script: pip install docker-compose
      script:
        - docker-compose up --build

    - stage: "Test-Script"
      script:
        - python3 ./Test-Script/Test.py
