version: "3.8"
services:
  web:
    image: jnewton1452/group-zero:latest
    ports:
      - "5000:5000"


  redis:
    image: redis
    volumes:
      - my_volume:/tmp/my_data
 

volumes:
  my_volume: {}
