version: "3.9"
services:
  web:
    image: jnewton1452/group-zero:latest
    build:
      context: .
    ports:
      - "5000:5000"


  redis:
    image: redis:alpine
    volumes:
      - my_volume:/tmp/my_data
 

volumes:
  my_volume: {}
