version: "3.9"
        services:
                api:
                        build: .
                ports:
                        - "80:80"
                redis:
                        image: "redis:alpine"