version: "3.8"
services:
  web:
    build: ./
    image: jnewton1452/travis-api-pipeline
    ports:
      - "5000:5000"
  redis:
    image: redis
    volumes:
      - my_volume:/tmp/my_data
        # platform: linux/amd64

volumes:
  my_volume: {}
