version: "3"

services:
        api:
        image: jnewton1452/group-zero:latest
        entrypoint: python app.py
          ports:
          - '80:80'

        redis:
                image: redis
                container_name: redis-container
                ports:
                  - "6379:6379"
