version: "3.9"
services:
  web:
    image: jgaecke/group-zero:latest
    build:
      context: .
    ports:
      - "5000:5000"
    platform: linux/arm64

  redis:
    image: redis:alpine
    volumes:
      - my_volume:/tmp/my_data
    platform: linux/arm64

volumes:
  my_volume: {}
